-- =====================================================================
-- NEKO Edu - Smart English Center Management Platform (C1SE.77)
-- 01_schema.sql - Tạo cấu trúc (DROP & CREATE, dùng cho database mới)
-- Target : PostgreSQL 14+  |  Generated: 2026-10-01
-- Owner  : Database - phamtngochuyen3@dtu.edu.vn
-- =====================================================================
SET client_min_messages = warning;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

DROP VIEW IF EXISTS v_student_tuition_summary CASCADE;
DROP VIEW IF EXISTS v_attendance_monthly CASCADE;
DROP VIEW IF EXISTS v_finance_monthly CASCADE;
DROP VIEW IF EXISTS v_lead_funnel_monthly CASCADE;
DROP VIEW IF EXISTS v_staff_schedule CASCADE;
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS policy_documents CASCADE;
DROP TABLE IF EXISTS ai_alerts CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS finance_transactions CASCADE;
DROP TABLE IF EXISTS finance_categories CASCADE;
DROP TABLE IF EXISTS staff_payrolls CASCADE;
DROP TABLE IF EXISTS receipts CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS tuition_invoices CASCADE;
DROP TABLE IF EXISTS student_discounts CASCADE;
DROP TABLE IF EXISTS discount_policies CASCADE;
DROP TABLE IF EXISTS student_requests CASCADE;
DROP TABLE IF EXISTS attendances CASCADE;
DROP TABLE IF EXISTS class_sessions CASCADE;
DROP TABLE IF EXISTS class_enrollments CASCADE;
DROP TABLE IF EXISTS class_schedules CASCADE;
DROP TABLE IF EXISTS classes CASCADE;
DROP TABLE IF EXISTS rooms CASCADE;
DROP TABLE IF EXISTS courses CASCADE;
DROP TABLE IF EXISTS admission_leads CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS levels CASCADE;
DROP TABLE IF EXISTS guardians CASCADE;
DROP TABLE IF EXISTS staff_profiles CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS roles CASCADE;

-- Danh mục vai trò hệ thống (RBAC).
CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_roles_code UNIQUE (code),
    CONSTRAINT ck_roles_code CHECK (code IN ('MANAGER', 'LECTURER', 'TEACHING_ASSISTANT', 'STUDENT_PARENT'))
);
COMMENT ON TABLE roles IS 'Danh mục vai trò hệ thống (RBAC).';
COMMENT ON COLUMN roles.id IS 'Khóa chính, tự tăng';
COMMENT ON COLUMN roles.code IS 'Mã vai trò dùng trong code (Spring Security authority)';
COMMENT ON COLUMN roles.name IS 'Tên hiển thị';
COMMENT ON COLUMN roles.description IS 'Mô tả quyền hạn';
COMMENT ON COLUMN roles.created_at IS 'Thời điểm tạo bản ghi';

-- Tài khoản đăng nhập của mọi actor. Mỗi học viên có 1 tài khoản dùng chung Student/Parent.
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(150),
    password_hash VARCHAR(100) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    phone VARCHAR(10),
    role_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT fk_users_role_id FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE RESTRICT,
    CONSTRAINT ck_users_phone CHECK (phone ~ '^0[0-9]{9}$'),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'LOCKED', 'INACTIVE'))
);
COMMENT ON TABLE users IS 'Tài khoản đăng nhập của mọi actor. Mỗi học viên có 1 tài khoản dùng chung Student/Parent.';
COMMENT ON COLUMN users.id IS 'Khóa chính, tự tăng';
COMMENT ON COLUMN users.username IS 'Tên đăng nhập';
COMMENT ON COLUMN users.email IS 'Email (bắt buộc với nhân sự, có thể trống với học viên)';
COMMENT ON COLUMN users.password_hash IS 'Mật khẩu đã băm BCrypt';
COMMENT ON COLUMN users.full_name IS 'Họ tên chủ tài khoản';
COMMENT ON COLUMN users.phone IS 'Số điện thoại 10 số';
COMMENT ON COLUMN users.role_id IS 'Vai trò';
COMMENT ON COLUMN users.status IS 'Trạng thái tài khoản';
COMMENT ON COLUMN users.last_login_at IS 'Lần đăng nhập gần nhất';
COMMENT ON COLUMN users.created_at IS 'Thời điểm tạo bản ghi';
COMMENT ON COLUMN users.updated_at IS 'Thời điểm cập nhật gần nhất';
CREATE INDEX ix_users_role_id ON users(role_id);

-- Hồ sơ nhân sự (Manager, Lecturer, Teaching Assistant); dùng cho phân công lớp và tính lương.
CREATE TABLE staff_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    staff_code VARCHAR(20) NOT NULL,
    position VARCHAR(30) NOT NULL,
    specialization VARCHAR(200),
    rate_per_session NUMERIC(12,0) NOT NULL DEFAULT 0,
    hire_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_staff_profiles_user_id UNIQUE (user_id),
    CONSTRAINT uq_staff_profiles_staff_code UNIQUE (staff_code),
    CONSTRAINT fk_staff_profiles_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT ck_staff_profiles_position CHECK (position IN ('MANAGER', 'LECTURER', 'TEACHING_ASSISTANT')),
    CONSTRAINT ck_staff_profiles_rate_per_session CHECK (rate_per_session >= 0),
    CONSTRAINT ck_staff_profiles_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);
COMMENT ON TABLE staff_profiles IS 'Hồ sơ nhân sự (Manager, Lecturer, Teaching Assistant); dùng cho phân công lớp và tính lương.';
COMMENT ON COLUMN staff_profiles.id IS 'Khóa chính, tự tăng';
COMMENT ON COLUMN staff_profiles.user_id IS 'Tài khoản tương ứng (1-1)';
COMMENT ON COLUMN staff_profiles.staff_code IS 'Mã nhân sự (MG01, GV01, TG01)';
COMMENT ON COLUMN staff_profiles.position IS 'Chức danh';
COMMENT ON COLUMN staff_profiles.specialization IS 'Chuyên môn / chứng chỉ';
COMMENT ON COLUMN staff_profiles.rate_per_session IS 'Đơn giá lương mỗi buổi dạy (VNĐ); 0 với Manager';
COMMENT ON COLUMN staff_profiles.hire_date IS 'Ngày vào làm';
COMMENT ON COLUMN staff_profiles.status IS 'Trạng thái làm việc';
COMMENT ON COLUMN staff_profiles.created_at IS 'Thời điểm tạo bản ghi';

-- Phụ huynh/người giám hộ. Anh chị em ruột dùng chung 1 guardian (theo SĐT trong file nguồn).
CREATE TABLE guardians (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    phone VARCHAR(10) NOT NULL,
    email VARCHAR(150),
    relationship VARCHAR(20) NOT NULL,
    address VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_guardians_phone UNIQUE (phone),
    CONSTRAINT ck_guardians_phone CHECK (phone ~ '^0[0-9]{9}$'),
    CONSTRAINT ck_guardians_relationship CHECK (relationship IN ('FATHER', 'MOTHER', 'GUARDIAN'))
);
COMMENT ON TABLE guardians IS 'Phụ huynh/người giám hộ. Anh chị em ruột dùng chung 1 guardian (theo SĐT trong file nguồn).';
COMMENT ON COLUMN guardians.id IS 'Khóa chính, tự tăng';
COMMENT ON COLUMN guardians.full_name IS 'Họ tên phụ huynh';
COMMENT ON COLUMN guardians.phone IS 'SĐT liên hệ (khóa nghiệp vụ để nhận diện gia đình)';
COMMENT ON COLUMN guardians.email IS 'Email phụ huynh';
COMMENT ON COLUMN guardians.relationship IS 'Quan hệ với học viên';
COMMENT ON COLUMN guardians.address IS 'Địa chỉ';
COMMENT ON COLUMN guardians.created_at IS 'Thời điểm tạo bản ghi';

-- Cấp độ học theo độ tuổi (KINDY → TEEN 3).
CREATE TABLE levels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20) NOT NULL,
    name VARCHAR(100) NOT NULL,
    min_age SMALLINT NOT NULL,
    max_age SMALLINT NOT NULL,
    sort_order SMALLINT NOT NULL,
    CONSTRAINT uq_levels_code UNIQUE (code),
    CONSTRAINT uq_levels_sort_order UNIQUE (sort_order),
    CONSTRAINT ck_levels_min_age CHECK (min_age >= 0),
    CONSTRAINT ck_levels_rule1 CHECK (max_age >= min_age)
);
COMMENT ON TABLE levels IS 'Cấp độ học theo độ tuổi (KINDY → TEEN 3).';
COMMENT ON COLUMN levels.id IS 'Khóa chính, tự tăng';
COMMENT ON COLUMN levels.code IS 'Mã level, giữ đúng giá trị file nguồn';
COMMENT ON COLUMN levels.name IS 'Tên level';
COMMENT ON COLUMN levels.min_age IS 'Tuổi tối thiểu khuyến nghị';
COMMENT ON COLUMN levels.max_age IS 'Tuổi tối đa khuyến nghị';
COMMENT ON COLUMN levels.sort_order IS 'Thứ tự lộ trình';

-- Hồ sơ học viên. Import từ sheet DanhSachHocSinh.
CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_code VARCHAR(10) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    english_name VARCHAR(50),
    date_of_birth DATE NOT NULL,
    guardian_id BIGINT NOT NULL,
    user_id BIGINT,
    current_level_id BIGINT NOT NULL,
    enrolled_at DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    note VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_students_student_code UNIQUE (student_code),
    CONSTRAINT uq_students_user_id UNIQUE (user_id),
    CONSTRAINT fk_students_guardian_id FOREIGN KEY (guardian_id) REFERENCES guardians(id) ON DELETE RESTRICT,
    CONSTRAINT fk_students_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_students_current_level_id FOREIGN KEY (current_level_id) REFERENCES levels(id) ON DELETE RESTRICT,
    CONSTRAINT ck_students_status CHECK (status IN ('ACTIVE', 'ON_HOLD', 'DROPPED', 'GRADUATED')),
    CONSTRAINT ck_students_rule1 CHECK (enrolled_at > date_of_birth)
);
COMMENT ON TABLE students IS 'Hồ sơ học viên. Import từ sheet DanhSachHocSinh.';
COMMENT ON COLUMN students.id IS 'Khóa chính, tự tăng';
COMMENT ON COLUMN students.student_code IS 'Mã học sinh (HS001…)';
COMMENT ON COLUMN students.full_name IS 'Họ và tên';
COMMENT ON COLUMN students.english_name IS 'Tên tiếng Anh';
COMMENT ON COLUMN students.date_of_birth IS 'Ngày sinh';
COMMENT ON COLUMN students.guardian_id IS 'Phụ huynh';
COMMENT ON COLUMN students.user_id IS 'Tài khoản Student/Parent (1-1)';
COMMENT ON COLUMN students.current_level_id IS 'Level hiện tại';
COMMENT ON COLUMN students.enrolled_at IS 'Ngày vào học trung tâm (Thời gian vào học)';
COMMENT ON COLUMN students.status IS 'Trạng thái học';
COMMENT ON COLUMN students.note IS 'Ghi chú';
COMMENT ON COLUMN students.created_at IS 'Thời điểm tạo bản ghi';
COMMENT ON COLUMN students.updated_at IS 'Thời điểm cập nhật gần nhất';
CREATE INDEX ix_students_guardian_id ON students(guardian_id);
CREATE INDEX ix_students_current_level_id ON students(current_level_id);

-- Phiếu tuyển sinh/tư vấn. Lead ENROLLED liên kết tới students; dữ liệu nguồn cho AI gợi ý thời điểm tuyển sinh.
CREATE TABLE admission_leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_code VARCHAR(20) NOT NULL,
    child_full_name VARCHAR(100) NOT NULL,
    child_dob DATE,
    guardian_name VARCHAR(100) NOT NULL,
    guardian_phone VARCHAR(10) NOT NULL,
    source VARCHAR(20) NOT NULL,
    interested_level_id BIGINT,
    placement_score NUMERIC(4,1),
    status VARCHAR(20) NOT NULL,
    student_id BIGINT,
    consultant_user_id BIGINT,
    converted_at DATE,
    note VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_admission_leads_lead_code UNIQUE (lead_code),
    CONSTRAINT uq_admission_leads_student_id UNIQUE (student_id),
    CONSTRAINT fk_admission_leads_interested_level_id FOREIGN KEY (interested_level_id) REFERENCES levels(id) ON DELETE SET NULL,
    CONSTRAINT fk_admission_leads_student_id FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE RESTRICT,
    CONSTRAINT fk_admission_leads_consultant_user_id FOREIGN KEY (consultant_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT ck_admission_leads_guardian_phone CHECK (guardian_phone ~ '^0[0-9]{9}$'),
    CONSTRAINT ck_admission_leads_source CHECK (source IN ('FACEBOOK', 'ZALO', 'WEBSITE', 'REFERRAL', 'WALK_IN', 'SCHOOL_EVENT')),
    CONSTRAINT ck_admission_leads_placement_score CHECK (placement_score BETWEEN 0 AND 10),
    CONSTRAINT ck_admission_leads_status CHECK (status IN ('NEW', 'CONTACTED', 'TESTED', 'ENROLLED', 'LOST')),
    CONSTRAINT ck_admission_leads_rule1 CHECK ((status = 'ENROLLED') = (student_id IS NOT NULL)),
    CONSTRAINT ck_admission_leads_rule2 CHECK ((status = 'ENROLLED') = (converted_at IS NOT NULL))
);
COMMENT ON TABLE admission_leads IS 'Phiếu tuyển sinh/tư vấn. Lead ENROLLED liên kết tới students; dữ liệu nguồn cho AI gợi ý thời điểm tuyển sinh.';
COMMENT ON COLUMN admission_leads.id IS 'Khóa chính, tự tăng';
COMMENT ON COLUMN admission_leads.lead_code IS 'Mã phiếu (LD-YYYYMM-xxxx)';
COMMENT ON COLUMN admission_leads.child_full_name IS 'Tên trẻ được tư vấn';
COMMENT ON COLUMN admission_leads.child_dob IS 'Ngày sinh trẻ';
COMMENT ON COLUMN admission_leads.guardian_name IS 'Tên phụ huynh liên hệ';
COMMENT ON COLUMN admission_leads.guardian_phone IS 'SĐT phụ huynh';
COMMENT ON COLUMN admission_leads.source IS 'Kênh tiếp cận';
COMMENT ON COLUMN admission_leads.interested_level_id IS 'Level dự kiến';
COMMENT ON COLUMN admission_leads.placement_score IS 'Điểm test đầu vào (0–10)';
COMMENT ON COLUMN admission_leads.status IS 'Trạng thái phễu tuyển sinh';
COMMENT ON COLUMN admission_leads.student_id IS 'Học viên được tạo khi chốt (chỉ khi ENROLLED)';
COMMENT ON COLUMN admission_leads.consultant_user_id IS 'Người tư vấn';
COMMENT ON COLUMN admission_leads.converted_at IS 'Ngày chốt nhập học';
COMMENT ON COLUMN admission_leads.note IS 'Ghi chú tư vấn';
COMMENT ON COLUMN admission_leads.created_at IS 'Thời điểm tạo bản ghi';
CREATE INDEX ix_admission_leads_interested_level_id ON admission_leads(interested_level_id);
CREATE INDEX ix_admission_leads_consultant_user_id ON admission_leads(consultant_user_id);

-- Khóa học (chương trình) theo level, kèm học phí chuẩn theo tháng.
CREATE TABLE courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_code VARCHAR(20) NOT NULL,
    level_id BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(1000),
    sessions_per_week SMALLINT NOT NULL,
    session_minutes SMALLINT NOT NULL,
    monthly_fee NUMERIC(12,0) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_courses_course_code UNIQUE (course_code),
    CONSTRAINT fk_courses_level_id FOREIGN KEY (level_id) REFERENCES levels(id) ON DELETE RESTRICT,
    CONSTRAINT ck_courses_sessions_per_week CHECK (sessions_per_week BETWEEN 1 AND 7),
    CONSTRAINT ck_courses_session_minutes CHECK (session_minutes > 0),
    CONSTRAINT ck_courses_monthly_fee CHECK (monthly_fee >= 0),
    CONSTRAINT ck_courses_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);
COMMENT ON TABLE courses IS 'Khóa học (chương trình) theo level, kèm học phí chuẩn theo tháng.';
COMMENT ON COLUMN courses.id IS 'Khóa chính, tự tăng';
COMMENT ON COLUMN courses.course_code IS 'Mã khóa học';
COMMENT ON COLUMN courses.level_id IS 'Level';
COMMENT ON COLUMN courses.name IS 'Tên khóa học';
COMMENT ON COLUMN courses.description IS 'Mô tả nội dung';
COMMENT ON COLUMN courses.sessions_per_week IS 'Số buổi/tuần';
COMMENT ON COLUMN courses.session_minutes IS 'Thời lượng 1 buổi (phút)';
COMMENT ON COLUMN courses.monthly_fee IS 'Học phí gốc/tháng (VNĐ)';
COMMENT ON COLUMN courses.status IS 'Trạng thái mở bán';
COMMENT ON COLUMN courses.created_at IS 'Thời điểm tạo bản ghi';
CREATE INDEX ix_courses_level_id ON courses(level_id);

-- Phòng học.
CREATE TABLE rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(10) NOT NULL,
    name VARCHAR(100) NOT NULL,
    capacity SMALLINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
    CONSTRAINT uq_rooms_code UNIQUE (code),
    CONSTRAINT ck_rooms_capacity CHECK (capacity > 0),
    CONSTRAINT ck_rooms_status CHECK (status IN ('AVAILABLE', 'MAINTENANCE'))
);
COMMENT ON TABLE rooms IS 'Phòng học.';
COMMENT ON COLUMN rooms.id IS 'Khóa chính, tự tăng';
COMMENT ON COLUMN rooms.code IS 'Mã phòng';
COMMENT ON COLUMN rooms.name IS 'Tên phòng';
COMMENT ON COLUMN rooms.capacity IS 'Sức chứa';
COMMENT ON COLUMN rooms.status IS 'Trạng thái';

-- Lớp học cụ thể của một khóa; tên lớp giữ đúng file nguồn (Kindy A, Kid 1A…).
CREATE TABLE classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_code VARCHAR(20) NOT NULL,
    name VARCHAR(50) NOT NULL,
    course_id BIGINT NOT NULL,
    lecturer_id BIGINT NOT NULL,
    assistant_id BIGINT,
    default_room_id BIGINT NOT NULL,
    max_students SMALLINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_classes_class_code UNIQUE (class_code),
    CONSTRAINT uq_classes_name UNIQUE (name),
    CONSTRAINT fk_classes_course_id FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE RESTRICT,
    CONSTRAINT fk_classes_lecturer_id FOREIGN KEY (lecturer_id) REFERENCES staff_profiles(id) ON DELETE RESTRICT,
    CONSTRAINT fk_classes_assistant_id FOREIGN KEY (assistant_id) REFERENCES staff_profiles(id) ON DELETE SET NULL,
    CONSTRAINT fk_classes_default_room_id FOREIGN KEY (default_room_id) REFERENCES rooms(id) ON DELETE RESTRICT,
    CONSTRAINT ck_classes_max_students CHECK (max_students > 0),
    CONSTRAINT ck_classes_status CHECK (status IN ('PLANNED', 'ONGOING', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT ck_classes_rule1 CHECK (end_date > start_date),
    CONSTRAINT ck_classes_rule2 CHECK (assistant_id IS NULL OR assistant_id <> lecturer_id)
);
COMMENT ON TABLE classes IS 'Lớp học cụ thể của một khóa; tên lớp giữ đúng file nguồn (Kindy A, Kid 1A…).';
COMMENT ON COLUMN classes.id IS 'Khóa chính, tự tăng';
COMMENT ON COLUMN classes.class_code IS 'Mã lớp (KINDY-A-2026…)';
COMMENT ON COLUMN classes.name IS 'Tên lớp';
COMMENT ON COLUMN classes.course_id IS 'Khóa học';
COMMENT ON COLUMN classes.lecturer_id IS 'Giảng viên phụ trách';
COMMENT ON COLUMN classes.assistant_id IS 'Trợ giảng (nếu có)';
COMMENT ON COLUMN classes.default_room_id IS 'Phòng mặc định';
COMMENT ON COLUMN classes.max_students IS 'Sĩ số tối đa';
COMMENT ON COLUMN classes.start_date IS 'Ngày khai giảng';
COMMENT ON COLUMN classes.end_date IS 'Ngày kết thúc dự kiến';
COMMENT ON COLUMN classes.status IS 'Trạng thái lớp';
COMMENT ON COLUMN classes.created_at IS 'Thời điểm tạo bản ghi';
CREATE INDEX ix_classes_course_id ON classes(course_id);
CREATE INDEX ix_classes_lecturer_id ON classes(lecturer_id);
CREATE INDEX ix_classes_assistant_id ON classes(assistant_id);
CREATE INDEX ix_classes_default_room_id ON classes(default_room_id);

-- Lịch học lặp hằng tuần của lớp (dùng để sinh class_sessions).
CREATE TABLE class_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id BIGINT NOT NULL,
    day_of_week SMALLINT NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    room_id BIGINT NOT NULL,
    CONSTRAINT uq_class_schedules_class_id_day_of_week_start_time UNIQUE (class_id, day_of_week, start_time),
    CONSTRAINT fk_class_schedules_class_id FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE,
    CONSTRAINT fk_class_schedules_room_id FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE RESTRICT,
    CONSTRAINT ck_class_schedules_day_of_week CHECK (day_of_week BETWEEN 1 AND 7),
    CONSTRAINT ck_class_schedules_rule1 CHECK (end_time > start_time)
);
COMMENT ON TABLE class_schedules IS 'Lịch học lặp hằng tuần của lớp (dùng để sinh class_sessions).';
COMMENT ON COLUMN class_schedules.id IS 'Khóa chính, tự tăng';
COMMENT ON COLUMN class_schedules.class_id IS 'Lớp';
COMMENT ON COLUMN class_schedules.day_of_week IS 'Thứ trong tuần theo ISO: 1=Thứ 2 … 7=Chủ nhật';
COMMENT ON COLUMN class_schedules.start_time IS 'Giờ bắt đầu';
COMMENT ON COLUMN class_schedules.end_time IS 'Giờ kết thúc';
COMMENT ON COLUMN class_schedules.room_id IS 'Phòng';
CREATE INDEX ix_class_schedules_class_id ON class_schedules(class_id);
CREATE INDEX ix_class_schedules_room_id ON class_schedules(room_id);

-- Học viên thuộc lớp nào (lịch sử chuyển lớp giữ ở đây).
CREATE TABLE class_enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    enrolled_date DATE NOT NULL,
    left_date DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_class_enrollments_class_id_student_id UNIQUE (class_id, student_id),
    CONSTRAINT fk_class_enrollments_class_id FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE RESTRICT,
    CONSTRAINT fk_class_enrollments_student_id FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE RESTRICT,
    CONSTRAINT ck_class_enrollments_status CHECK (status IN ('ACTIVE', 'TRANSFERRED', 'DROPPED', 'COMPLETED')),
    CONSTRAINT ck_class_enrollments_rule1 CHECK (left_date IS NULL OR left_date >= enrolled_date)
);
COMMENT ON TABLE class_enrollments IS 'Học viên thuộc lớp nào (lịch sử chuyển lớp giữ ở đây).';
COMMENT ON COLUMN class_enrollments.id IS 'Khóa chính, tự tăng';
COMMENT ON COLUMN class_enrollments.class_id IS 'Lớp';
COMMENT ON COLUMN class_enrollments.student_id IS 'Học viên';
COMMENT ON COLUMN class_enrollments.enrolled_date IS 'Ngày vào lớp';
COMMENT ON COLUMN class_enrollments.left_date IS 'Ngày rời lớp';
COMMENT ON COLUMN class_enrollments.status IS 'Trạng thái trong lớp';
COMMENT ON COLUMN class_enrollments.created_at IS 'Thời điểm tạo bản ghi';
CREATE INDEX ix_class_enrollments_class_id ON class_enrollments(class_id);
CREATE INDEX ix_class_enrollments_student_id ON class_enrollments(student_id);

-- Từng buổi học thực tế (sinh từ lịch). Nguồn cho điểm danh, lịch dạy GV/TG và lương.
CREATE TABLE class_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id BIGINT NOT NULL,
    session_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    room_id BIGINT NOT NULL,
    lecturer_id BIGINT NOT NULL,
    assistant_id BIGINT,
    status VARCHAR(20) NOT NULL,
    note VARCHAR(255),
    CONSTRAINT uq_class_sessions_class_id_session_date_start_time UNIQUE (class_id, session_date, start_time),
    CONSTRAINT fk_class_sessions_class_id FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE,
    CONSTRAINT fk_class_sessions_room_id FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE RESTRICT,
    CONSTRAINT fk_class_sessions_lecturer_id FOREIGN KEY (lecturer_id) REFERENCES staff_profiles(id) ON DELETE RESTRICT,
    CONSTRAINT fk_class_sessions_assistant_id FOREIGN KEY (assistant_id) REFERENCES staff_profiles(id) ON DELETE SET NULL,
    CONSTRAINT ck_class_sessions_status CHECK (status IN ('SCHEDULED', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT ck_class_sessions_rule1 CHECK (end_time > start_time)
);
COMMENT ON TABLE class_sessions IS 'Từng buổi học thực tế (sinh từ lịch). Nguồn cho điểm danh, lịch dạy GV/TG và lương.';
COMMENT ON COLUMN class_sessions.id IS 'Khóa chính, tự tăng';
COMMENT ON COLUMN class_sessions.class_id IS 'Lớp';
COMMENT ON COLUMN class_sessions.session_date IS 'Ngày học';
COMMENT ON COLUMN class_sessions.start_time IS 'Giờ bắt đầu';
COMMENT ON COLUMN class_sessions.end_time IS 'Giờ kết thúc';
COMMENT ON COLUMN class_sessions.room_id IS 'Phòng';
COMMENT ON COLUMN class_sessions.lecturer_id IS 'GV dạy buổi này (có thể dạy thay)';
COMMENT ON COLUMN class_sessions.assistant_id IS 'TG hỗ trợ buổi này';
COMMENT ON COLUMN class_sessions.status IS 'Trạng thái buổi';
COMMENT ON COLUMN class_sessions.note IS 'Ghi chú (lý do hủy…)';
CREATE INDEX ix_class_sessions_class_id ON class_sessions(class_id);
CREATE INDEX ix_class_sessions_room_id ON class_sessions(room_id);
CREATE INDEX ix_class_sessions_lecturer_id ON class_sessions(lecturer_id);
CREATE INDEX ix_class_sessions_assistant_id ON class_sessions(assistant_id);

-- Điểm danh thủ công từng học viên trong từng buổi (chỉ buổi COMPLETED).
CREATE TABLE attendances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    recorded_by BIGINT NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL,
    note VARCHAR(255),
    CONSTRAINT uq_attendances_session_id_student_id UNIQUE (session_id, student_id),
    CONSTRAINT fk_attendances_session_id FOREIGN KEY (session_id) REFERENCES class_sessions(id) ON DELETE CASCADE,
    CONSTRAINT fk_attendances_student_id FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE RESTRICT,
    CONSTRAINT fk_attendances_recorded_by FOREIGN KEY (recorded_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT ck_attendances_status CHECK (status IN ('PRESENT', 'LATE', 'ABSENT', 'EXCUSED'))
);
COMMENT ON TABLE attendances IS 'Điểm danh thủ công từng học viên trong từng buổi (chỉ buổi COMPLETED).';
COMMENT ON COLUMN attendances.id IS 'Khóa chính, tự tăng';
COMMENT ON COLUMN attendances.session_id IS 'Buổi học';
COMMENT ON COLUMN attendances.student_id IS 'Học viên';
COMMENT ON COLUMN attendances.status IS 'Kết quả điểm danh';
COMMENT ON COLUMN attendances.recorded_by IS 'Người điểm danh (GV hoặc TG)';
COMMENT ON COLUMN attendances.recorded_at IS 'Thời điểm ghi nhận';
COMMENT ON COLUMN attendances.note IS 'Ghi chú';
CREATE INDEX ix_attendances_session_id ON attendances(session_id);
CREATE INDEX ix_attendances_student_id ON attendances(student_id);
CREATE INDEX ix_attendances_recorded_by ON attendances(recorded_by);

-- Đơn xin nghỉ (LEAVE) / bảo lưu (HOLD) gửi từ tài khoản Student/Parent.
CREATE TABLE student_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_code VARCHAR(20) NOT NULL,
    student_id BIGINT NOT NULL,
    request_type VARCHAR(10) NOT NULL,
    from_date DATE NOT NULL,
    to_date DATE NOT NULL,
    reason VARCHAR(500) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    submitted_by BIGINT NOT NULL,
    reviewed_by BIGINT,
    reviewed_at TIMESTAMPTZ,
    review_note VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_student_requests_request_code UNIQUE (request_code),
    CONSTRAINT fk_student_requests_student_id FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE RESTRICT,
    CONSTRAINT fk_student_requests_submitted_by FOREIGN KEY (submitted_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_student_requests_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT ck_student_requests_request_type CHECK (request_type IN ('LEAVE', 'HOLD')),
    CONSTRAINT ck_student_requests_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
    CONSTRAINT ck_student_requests_rule1 CHECK (to_date >= from_date),
    CONSTRAINT ck_student_requests_rule2 CHECK (status NOT IN ('APPROVED','REJECTED') OR (reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL))
);
COMMENT ON TABLE student_requests IS 'Đơn xin nghỉ (LEAVE) / bảo lưu (HOLD) gửi từ tài khoản Student/Parent.';
COMMENT ON COLUMN student_requests.id IS 'Khóa chính, tự tăng';
COMMENT ON COLUMN student_requests.request_code IS 'Mã đơn';
COMMENT ON COLUMN student_requests.student_id IS 'Học viên';
COMMENT ON COLUMN student_requests.request_type IS 'Loại đơn';
COMMENT ON COLUMN student_requests.from_date IS 'Từ ngày';
COMMENT ON COLUMN student_requests.to_date IS 'Đến ngày';
COMMENT ON COLUMN student_requests.reason IS 'Lý do';
COMMENT ON COLUMN student_requests.status IS 'Trạng thái xử lý';
COMMENT ON COLUMN student_requests.submitted_by IS 'Tài khoản gửi đơn';
COMMENT ON COLUMN student_requests.reviewed_by IS 'Manager duyệt';
COMMENT ON COLUMN student_requests.reviewed_at IS 'Thời điểm duyệt';
COMMENT ON COLUMN student_requests.review_note IS 'Ghi chú duyệt';
COMMENT ON COLUMN student_requests.created_at IS 'Thời điểm tạo bản ghi';
CREATE INDEX ix_student_requests_student_id ON student_requests(student_id);
CREATE INDEX ix_student_requests_submitted_by ON student_requests(submitted_by);
CREATE INDEX ix_student_requests_reviewed_by ON student_requests(reviewed_by);

-- Chính sách giảm giá (vd: giảm 10% khi có anh chị em cùng học).
CREATE TABLE discount_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL,
    name VARCHAR(150) NOT NULL,
    discount_type VARCHAR(10) NOT NULL,
    discount_value NUMERIC(12,2) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_discount_policies_code UNIQUE (code),
    CONSTRAINT ck_discount_policies_discount_type CHECK (discount_type IN ('PERCENT', 'AMOUNT')),
    CONSTRAINT ck_discount_policies_discount_value CHECK (discount_value > 0),
    CONSTRAINT ck_discount_policies_rule1 CHECK (discount_type <> 'PERCENT' OR discount_value <= 100)
);
COMMENT ON TABLE discount_policies IS 'Chính sách giảm giá (vd: giảm 10% khi có anh chị em cùng học).';
COMMENT ON COLUMN discount_policies.id IS 'Khóa chính, tự tăng';
COMMENT ON COLUMN discount_policies.code IS 'Mã chính sách';
COMMENT ON COLUMN discount_policies.name IS 'Tên chính sách';
COMMENT ON COLUMN discount_policies.discount_type IS 'PERCENT = theo %, AMOUNT = số tiền cố định';
COMMENT ON COLUMN discount_policies.discount_value IS 'Giá trị giảm (10 = 10% hoặc 100000 VNĐ)';
COMMENT ON COLUMN discount_policies.is_active IS 'Còn hiệu lực';
COMMENT ON COLUMN discount_policies.created_at IS 'Thời điểm tạo bản ghi';

-- Học viên được áp dụng chính sách giảm giá nào, trong thời gian nào.
CREATE TABLE student_discounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    discount_policy_id BIGINT NOT NULL,
    valid_from DATE NOT NULL,
    valid_to DATE,
    reason VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_student_discounts_student_id_discount_policy_id_valid_from UNIQUE (student_id, discount_policy_id, valid_from),
    CONSTRAINT fk_student_discounts_student_id FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
    CONSTRAINT fk_student_discounts_discount_policy_id FOREIGN KEY (discount_policy_id) REFERENCES discount_policies(id) ON DELETE RESTRICT,
    CONSTRAINT ck_student_discounts_rule1 CHECK (valid_to IS NULL OR valid_to >= valid_from)
);
COMMENT ON TABLE student_discounts IS 'Học viên được áp dụng chính sách giảm giá nào, trong thời gian nào.';
COMMENT ON COLUMN student_discounts.id IS 'Khóa chính, tự tăng';
COMMENT ON COLUMN student_discounts.student_id IS 'Học viên';
COMMENT ON COLUMN student_discounts.discount_policy_id IS 'Chính sách';
COMMENT ON COLUMN student_discounts.valid_from IS 'Áp dụng từ';
COMMENT ON COLUMN student_discounts.valid_to IS 'Áp dụng đến (NULL = không thời hạn)';
COMMENT ON COLUMN student_discounts.reason IS 'Căn cứ áp dụng';
COMMENT ON COLUMN student_discounts.created_at IS 'Thời điểm tạo bản ghi';
CREATE INDEX ix_student_discounts_student_id ON student_discounts(student_id);
CREATE INDEX ix_student_discounts_discount_policy_id ON student_discounts(discount_policy_id);

-- Phiếu học phí hằng tháng của từng học viên. Import từ sheet TheoDoiHocPhi.
CREATE TABLE tuition_invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_code VARCHAR(20) NOT NULL,
    student_id BIGINT NOT NULL,
    class_id BIGINT NOT NULL,
    billing_month DATE NOT NULL,
    base_amount NUMERIC(12,0) NOT NULL,
    discount_amount NUMERIC(12,0) NOT NULL DEFAULT 0,
    final_amount NUMERIC(12,0) NOT NULL,
    paid_amount NUMERIC(12,0) NOT NULL DEFAULT 0,
    due_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    generated_by VARCHAR(20) NOT NULL DEFAULT 'MANUAL',
    discount_policy_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_tuition_invoices_invoice_code UNIQUE (invoice_code),
    CONSTRAINT uq_tuition_invoices_student_id_billing_month UNIQUE (student_id, billing_month),
    CONSTRAINT fk_tuition_invoices_student_id FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE RESTRICT,
    CONSTRAINT fk_tuition_invoices_class_id FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE RESTRICT,
    CONSTRAINT fk_tuition_invoices_discount_policy_id FOREIGN KEY (discount_policy_id) REFERENCES discount_policies(id) ON DELETE SET NULL,
    CONSTRAINT ck_tuition_invoices_base_amount CHECK (base_amount >= 0),
    CONSTRAINT ck_tuition_invoices_discount_amount CHECK (discount_amount >= 0),
    CONSTRAINT ck_tuition_invoices_paid_amount CHECK (paid_amount >= 0),
    CONSTRAINT ck_tuition_invoices_status CHECK (status IN ('UNPAID', 'PARTIAL', 'PAID', 'CANCELLED')),
    CONSTRAINT ck_tuition_invoices_generated_by CHECK (generated_by IN ('MANUAL', 'IMPORT', 'AI_ENGINE')),
    CONSTRAINT ck_tuition_invoices_rule1 CHECK (final_amount = base_amount - discount_amount),
    CONSTRAINT ck_tuition_invoices_rule2 CHECK (paid_amount <= final_amount),
    CONSTRAINT ck_tuition_invoices_rule3 CHECK (due_date >= billing_month),
    CONSTRAINT ck_tuition_invoices_rule4 CHECK ((status = 'PAID') = (paid_amount = final_amount AND final_amount > 0)),
    CONSTRAINT ck_tuition_invoices_rule5 CHECK (status <> 'UNPAID' OR paid_amount = 0)
);
COMMENT ON TABLE tuition_invoices IS 'Phiếu học phí hằng tháng của từng học viên. Import từ sheet TheoDoiHocPhi.';
COMMENT ON COLUMN tuition_invoices.id IS 'Khóa chính, tự tăng';
COMMENT ON COLUMN tuition_invoices.invoice_code IS 'Mã phiếu (INV-YYYYMM-HSxxx)';
COMMENT ON COLUMN tuition_invoices.student_id IS 'Học viên';
COMMENT ON COLUMN tuition_invoices.class_id IS 'Lớp tính phí';
COMMENT ON COLUMN tuition_invoices.billing_month IS 'Tháng tính phí, luôn là ngày 01 của tháng';
COMMENT ON COLUMN tuition_invoices.base_amount IS 'Học phí gốc (VNĐ)';
COMMENT ON COLUMN tuition_invoices.discount_amount IS 'Tiền giảm (VNĐ)';
COMMENT ON COLUMN tuition_invoices.final_amount IS 'Phải nộp = gốc − giảm (VNĐ)';
COMMENT ON COLUMN tuition_invoices.paid_amount IS 'Đã thu (VNĐ), cập nhật theo payments';
COMMENT ON COLUMN tuition_invoices.due_date IS 'Hạn nộp';
COMMENT ON COLUMN tuition_invoices.status IS 'Trạng thái thanh toán';
COMMENT ON COLUMN tuition_invoices.generated_by IS 'Nguồn tạo phiếu';
COMMENT ON COLUMN tuition_invoices.discount_policy_id IS 'Chính sách giảm đã áp';
COMMENT ON COLUMN tuition_invoices.created_at IS 'Thời điểm tạo bản ghi';
CREATE INDEX ix_tuition_invoices_student_id ON tuition_invoices(student_id);
CREATE INDEX ix_tuition_invoices_class_id ON tuition_invoices(class_id);
CREATE INDEX ix_tuition_invoices_discount_policy_id ON tuition_invoices(discount_policy_id);

-- Giao dịch thu học phí (1 phiếu có thể thu nhiều lần).
CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_code VARCHAR(20) NOT NULL,
    invoice_id BIGINT NOT NULL,
    amount NUMERIC(12,0) NOT NULL,
    method VARCHAR(20) NOT NULL,
    paid_at TIMESTAMPTZ NOT NULL,
    received_by BIGINT,
    transaction_ref VARCHAR(50),
    note VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_payments_payment_code UNIQUE (payment_code),
    CONSTRAINT fk_payments_invoice_id FOREIGN KEY (invoice_id) REFERENCES tuition_invoices(id) ON DELETE RESTRICT,
    CONSTRAINT fk_payments_received_by FOREIGN KEY (received_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT ck_payments_amount CHECK (amount > 0),
    CONSTRAINT ck_payments_method CHECK (method IN ('CASH', 'BANK_TRANSFER', 'MOMO', 'VNPAY'))
);
COMMENT ON TABLE payments IS 'Giao dịch thu học phí (1 phiếu có thể thu nhiều lần).';
COMMENT ON COLUMN payments.id IS 'Khóa chính, tự tăng';
COMMENT ON COLUMN payments.payment_code IS 'Mã giao dịch';
COMMENT ON COLUMN payments.invoice_id IS 'Phiếu học phí';
COMMENT ON COLUMN payments.amount IS 'Số tiền thu (VNĐ)';
COMMENT ON COLUMN payments.method IS 'Hình thức thanh toán';
COMMENT ON COLUMN payments.paid_at IS 'Thời điểm thanh toán';
COMMENT ON COLUMN payments.received_by IS 'Nhân sự xác nhận thu';
COMMENT ON COLUMN payments.transaction_ref IS 'Mã tham chiếu ngân hàng/ví';
COMMENT ON COLUMN payments.note IS 'Ghi chú';
COMMENT ON COLUMN payments.created_at IS 'Thời điểm tạo bản ghi';
CREATE INDEX ix_payments_invoice_id ON payments(invoice_id);
CREATE INDEX ix_payments_received_by ON payments(received_by);

-- Biên lai phát hành cho mỗi giao dịch thu.
CREATE TABLE receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_no VARCHAR(20) NOT NULL,
    payment_id BIGINT NOT NULL,
    issued_at TIMESTAMPTZ NOT NULL,
    issued_by BIGINT,
    CONSTRAINT uq_receipts_receipt_no UNIQUE (receipt_no),
    CONSTRAINT uq_receipts_payment_id UNIQUE (payment_id),
    CONSTRAINT fk_receipts_payment_id FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE RESTRICT,
    CONSTRAINT fk_receipts_issued_by FOREIGN KEY (issued_by) REFERENCES users(id) ON DELETE SET NULL
);
COMMENT ON TABLE receipts IS 'Biên lai phát hành cho mỗi giao dịch thu.';
COMMENT ON COLUMN receipts.id IS 'Khóa chính, tự tăng';
COMMENT ON COLUMN receipts.receipt_no IS 'Số biên lai';
COMMENT ON COLUMN receipts.payment_id IS 'Giao dịch (1-1)';
COMMENT ON COLUMN receipts.issued_at IS 'Thời điểm phát hành';
COMMENT ON COLUMN receipts.issued_by IS 'Người phát hành';
CREATE INDEX ix_receipts_issued_by ON receipts(issued_by);

-- Bảng lương theo tháng của GV/TG, tính theo số buổi COMPLETED.
CREATE TABLE staff_payrolls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id BIGINT NOT NULL,
    payroll_month DATE NOT NULL,
    session_count SMALLINT NOT NULL,
    rate_per_session NUMERIC(12,0) NOT NULL,
    bonus NUMERIC(12,0) NOT NULL DEFAULT 0,
    deduction NUMERIC(12,0) NOT NULL DEFAULT 0,
    total_amount NUMERIC(12,0) NOT NULL,
    status VARCHAR(20) NOT NULL,
    approved_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_staff_payrolls_staff_id_payroll_month UNIQUE (staff_id, payroll_month),
    CONSTRAINT fk_staff_payrolls_staff_id FOREIGN KEY (staff_id) REFERENCES staff_profiles(id) ON DELETE RESTRICT,
    CONSTRAINT fk_staff_payrolls_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT ck_staff_payrolls_session_count CHECK (session_count >= 0),
    CONSTRAINT ck_staff_payrolls_rate_per_session CHECK (rate_per_session >= 0),
    CONSTRAINT ck_staff_payrolls_bonus CHECK (bonus >= 0),
    CONSTRAINT ck_staff_payrolls_deduction CHECK (deduction >= 0),
    CONSTRAINT ck_staff_payrolls_status CHECK (status IN ('DRAFT', 'APPROVED', 'PAID')),
    CONSTRAINT ck_staff_payrolls_rule1 CHECK (total_amount = session_count * rate_per_session + bonus - deduction)
);
COMMENT ON TABLE staff_payrolls IS 'Bảng lương theo tháng của GV/TG, tính theo số buổi COMPLETED.';
COMMENT ON COLUMN staff_payrolls.id IS 'Khóa chính, tự tăng';
COMMENT ON COLUMN staff_payrolls.staff_id IS 'Nhân sự';
COMMENT ON COLUMN staff_payrolls.payroll_month IS 'Tháng lương (ngày 01)';
COMMENT ON COLUMN staff_payrolls.session_count IS 'Số buổi đã dạy';
COMMENT ON COLUMN staff_payrolls.rate_per_session IS 'Đơn giá/buổi tại thời điểm tính';
COMMENT ON COLUMN staff_payrolls.bonus IS 'Thưởng';
COMMENT ON COLUMN staff_payrolls.deduction IS 'Khấu trừ';
COMMENT ON COLUMN staff_payrolls.total_amount IS 'Thực lĩnh = buổi × đơn giá + thưởng − khấu trừ';
COMMENT ON COLUMN staff_payrolls.status IS 'Trạng thái';
COMMENT ON COLUMN staff_payrolls.approved_by IS 'Manager duyệt';
COMMENT ON COLUMN staff_payrolls.created_at IS 'Thời điểm tạo bản ghi';
CREATE INDEX ix_staff_payrolls_staff_id ON staff_payrolls(staff_id);
CREATE INDEX ix_staff_payrolls_approved_by ON staff_payrolls(approved_by);

-- Danh mục thu/chi toàn trung tâm.
CREATE TABLE finance_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL,
    name VARCHAR(100) NOT NULL,
    txn_type VARCHAR(10) NOT NULL,
    CONSTRAINT uq_finance_categories_code UNIQUE (code),
    CONSTRAINT ck_finance_categories_txn_type CHECK (txn_type IN ('INCOME', 'EXPENSE'))
);
COMMENT ON TABLE finance_categories IS 'Danh mục thu/chi toàn trung tâm.';
COMMENT ON COLUMN finance_categories.id IS 'Khóa chính, tự tăng';
COMMENT ON COLUMN finance_categories.code IS 'Mã danh mục';
COMMENT ON COLUMN finance_categories.name IS 'Tên danh mục';
COMMENT ON COLUMN finance_categories.txn_type IS 'INCOME = thu, EXPENSE = chi';

-- Sổ thu/chi toàn trung tâm. Thu học phí liên kết payments; chi lương liên kết staff_payrolls.
CREATE TABLE finance_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    txn_code VARCHAR(25) NOT NULL,
    category_id BIGINT NOT NULL,
    amount NUMERIC(14,0) NOT NULL,
    txn_date DATE NOT NULL,
    description VARCHAR(255) NOT NULL,
    payment_id BIGINT,
    payroll_id BIGINT,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_finance_transactions_txn_code UNIQUE (txn_code),
    CONSTRAINT uq_finance_transactions_payment_id UNIQUE (payment_id),
    CONSTRAINT uq_finance_transactions_payroll_id UNIQUE (payroll_id),
    CONSTRAINT fk_finance_transactions_category_id FOREIGN KEY (category_id) REFERENCES finance_categories(id) ON DELETE RESTRICT,
    CONSTRAINT fk_finance_transactions_payment_id FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE RESTRICT,
    CONSTRAINT fk_finance_transactions_payroll_id FOREIGN KEY (payroll_id) REFERENCES staff_payrolls(id) ON DELETE RESTRICT,
    CONSTRAINT fk_finance_transactions_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT ck_finance_transactions_amount CHECK (amount > 0),
    CONSTRAINT ck_finance_transactions_rule1 CHECK (payment_id IS NULL OR payroll_id IS NULL)
);
COMMENT ON TABLE finance_transactions IS 'Sổ thu/chi toàn trung tâm. Thu học phí liên kết payments; chi lương liên kết staff_payrolls.';
COMMENT ON COLUMN finance_transactions.id IS 'Khóa chính, tự tăng';
COMMENT ON COLUMN finance_transactions.txn_code IS 'Mã chứng từ';
COMMENT ON COLUMN finance_transactions.category_id IS 'Danh mục';
COMMENT ON COLUMN finance_transactions.amount IS 'Số tiền (VNĐ, luôn dương; chiều thu/chi theo danh mục)';
COMMENT ON COLUMN finance_transactions.txn_date IS 'Ngày chứng từ';
COMMENT ON COLUMN finance_transactions.description IS 'Diễn giải';
COMMENT ON COLUMN finance_transactions.payment_id IS 'Giao dịch học phí liên quan';
COMMENT ON COLUMN finance_transactions.payroll_id IS 'Bảng lương liên quan';
COMMENT ON COLUMN finance_transactions.created_by IS 'Người ghi sổ';
COMMENT ON COLUMN finance_transactions.created_at IS 'Thời điểm tạo bản ghi';
CREATE INDEX ix_finance_transactions_category_id ON finance_transactions(category_id);
CREATE INDEX ix_finance_transactions_created_by ON finance_transactions(created_by);

-- Thông báo gửi tới từng tài khoản (broadcast được fan-out thành nhiều dòng).
CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id BIGINT NOT NULL,
    notification_type VARCHAR(20) NOT NULL,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    related_invoice_id BIGINT,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    read_at TIMESTAMPTZ,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_notifications_recipient_user_id FOREIGN KEY (recipient_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_notifications_related_invoice_id FOREIGN KEY (related_invoice_id) REFERENCES tuition_invoices(id) ON DELETE SET NULL,
    CONSTRAINT fk_notifications_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT ck_notifications_notification_type CHECK (notification_type IN ('TUITION', 'SCHEDULE', 'REQUEST', 'GENERAL')),
    CONSTRAINT ck_notifications_rule1 CHECK (is_read = (read_at IS NOT NULL))
);
COMMENT ON TABLE notifications IS 'Thông báo gửi tới từng tài khoản (broadcast được fan-out thành nhiều dòng).';
COMMENT ON COLUMN notifications.id IS 'Khóa chính, tự tăng';
COMMENT ON COLUMN notifications.recipient_user_id IS 'Người nhận';
COMMENT ON COLUMN notifications.notification_type IS 'Loại';
COMMENT ON COLUMN notifications.title IS 'Tiêu đề';
COMMENT ON COLUMN notifications.content IS 'Nội dung';
COMMENT ON COLUMN notifications.related_invoice_id IS 'Phiếu học phí liên quan';
COMMENT ON COLUMN notifications.is_read IS 'Đã đọc';
COMMENT ON COLUMN notifications.read_at IS 'Thời điểm đọc';
COMMENT ON COLUMN notifications.created_by IS 'Người/hệ thống tạo';
COMMENT ON COLUMN notifications.created_at IS 'Thời điểm tạo bản ghi';
CREATE INDEX ix_notifications_recipient_user_id ON notifications(recipient_user_id);
CREATE INDEX ix_notifications_related_invoice_id ON notifications(related_invoice_id);
CREATE INDEX ix_notifications_created_by ON notifications(created_by);

-- Cảnh báo/gợi ý do AI (hoặc rule) sinh ra, chờ Manager review.
CREATE TABLE ai_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_type VARCHAR(30) NOT NULL,
    severity VARCHAR(10) NOT NULL,
    student_id BIGINT,
    title VARCHAR(200) NOT NULL,
    detail TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'NEW',
    source VARCHAR(20) NOT NULL,
    reviewed_by BIGINT,
    reviewed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_ai_alerts_student_id FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
    CONSTRAINT fk_ai_alerts_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT ck_ai_alerts_alert_type CHECK (alert_type IN ('DEBT_RISK', 'LOW_ATTENDANCE', 'TUITION_DATA_ANOMALY', 'FINANCE_RISK', 'ENROLLMENT_RECOMMENDATION')),
    CONSTRAINT ck_ai_alerts_severity CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH')),
    CONSTRAINT ck_ai_alerts_status CHECK (status IN ('NEW', 'ACKNOWLEDGED', 'RESOLVED', 'DISMISSED')),
    CONSTRAINT ck_ai_alerts_source CHECK (source IN ('SEED', 'AI_ENGINE'))
);
COMMENT ON TABLE ai_alerts IS 'Cảnh báo/gợi ý do AI (hoặc rule) sinh ra, chờ Manager review.';
COMMENT ON COLUMN ai_alerts.id IS 'Khóa chính, tự tăng';
COMMENT ON COLUMN ai_alerts.alert_type IS 'Loại cảnh báo';
COMMENT ON COLUMN ai_alerts.severity IS 'Mức độ';
COMMENT ON COLUMN ai_alerts.student_id IS 'Học viên liên quan';
COMMENT ON COLUMN ai_alerts.title IS 'Tiêu đề';
COMMENT ON COLUMN ai_alerts.detail IS 'Diễn giải, số liệu căn cứ';
COMMENT ON COLUMN ai_alerts.status IS 'Trạng thái review';
COMMENT ON COLUMN ai_alerts.source IS 'SEED = dữ liệu mẫu, AI_ENGINE = do service AI sinh';
COMMENT ON COLUMN ai_alerts.reviewed_by IS 'Manager review';
COMMENT ON COLUMN ai_alerts.reviewed_at IS 'Thời điểm review';
COMMENT ON COLUMN ai_alerts.created_at IS 'Thời điểm tạo bản ghi';
CREATE INDEX ix_ai_alerts_student_id ON ai_alerts(student_id);
CREATE INDEX ix_ai_alerts_reviewed_by ON ai_alerts(reviewed_by);

-- Văn bản chính sách nội bộ làm kho tri thức cho RAG assistant.
CREATE TABLE policy_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_code VARCHAR(30) NOT NULL,
    title VARCHAR(200) NOT NULL,
    category VARCHAR(30) NOT NULL,
    content TEXT NOT NULL,
    version VARCHAR(10) NOT NULL,
    effective_date DATE NOT NULL,
    visibility VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_policy_documents_doc_code UNIQUE (doc_code),
    CONSTRAINT ck_policy_documents_category CHECK (category IN ('TUITION', 'ATTENDANCE', 'ADMISSION', 'HR', 'OPERATION')),
    CONSTRAINT ck_policy_documents_visibility CHECK (visibility IN ('MANAGER_ONLY', 'ALL_STAFF')),
    CONSTRAINT ck_policy_documents_status CHECK (status IN ('ACTIVE', 'ARCHIVED'))
);
COMMENT ON TABLE policy_documents IS 'Văn bản chính sách nội bộ làm kho tri thức cho RAG assistant.';
COMMENT ON COLUMN policy_documents.id IS 'Khóa chính, tự tăng';
COMMENT ON COLUMN policy_documents.doc_code IS 'Mã văn bản';
COMMENT ON COLUMN policy_documents.title IS 'Tiêu đề';
COMMENT ON COLUMN policy_documents.category IS 'Nhóm chính sách';
COMMENT ON COLUMN policy_documents.content IS 'Nội dung đầy đủ (Markdown)';
COMMENT ON COLUMN policy_documents.version IS 'Phiên bản';
COMMENT ON COLUMN policy_documents.effective_date IS 'Ngày hiệu lực';
COMMENT ON COLUMN policy_documents.visibility IS 'Phạm vi được truy vấn qua RAG';
COMMENT ON COLUMN policy_documents.status IS 'Trạng thái';
COMMENT ON COLUMN policy_documents.created_at IS 'Thời điểm tạo bản ghi';

-- Nhật ký thay đổi dữ liệu nhạy cảm (học phí, thanh toán, quyền, điểm).
CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT,
    action VARCHAR(20) NOT NULL,
    entity_name VARCHAR(50) NOT NULL,
    entity_id BIGINT,
    old_data JSONB,
    new_data JSONB,
    ip_address VARCHAR(45),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_audit_logs_actor_user_id FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT ck_audit_logs_action CHECK (action IN ('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'APPROVE'))
);
COMMENT ON TABLE audit_logs IS 'Nhật ký thay đổi dữ liệu nhạy cảm (học phí, thanh toán, quyền, điểm).';
COMMENT ON COLUMN audit_logs.id IS 'Khóa chính, tự tăng';
COMMENT ON COLUMN audit_logs.actor_user_id IS 'Người thực hiện';
COMMENT ON COLUMN audit_logs.action IS 'Hành động';
COMMENT ON COLUMN audit_logs.entity_name IS 'Tên bảng/đối tượng';
COMMENT ON COLUMN audit_logs.entity_id IS 'Id bản ghi bị tác động';
COMMENT ON COLUMN audit_logs.old_data IS 'Giá trị trước';
COMMENT ON COLUMN audit_logs.new_data IS 'Giá trị sau';
COMMENT ON COLUMN audit_logs.ip_address IS 'IP';
COMMENT ON COLUMN audit_logs.created_at IS 'Thời điểm tạo bản ghi';
CREATE INDEX ix_audit_logs_actor_user_id ON audit_logs(actor_user_id);
